#!/usr/bin/env bash
# omens of luck from around the world
counter=1
while [ $counter -le 20 ]
do
    case $counter in
    4)
        echo "bad luck from China";;
    9)
        echo "bad luck from Japan";;
    17)
        echo "bad luck from Italy";;
    *)
        echo $counter;;
    esac
    ((counter++))
done